lib/goodreaders_web/router.ex
defmodule GoodreadersWeb.Router do
  use GoodreadersWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", GoodreadersWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    
    resources "/users", UserController
    resources "/articles", ArticleController

  end
end

lib/goodreaders_web/templates/page/index.html.eex
<div class="container">
<div class="row">
  <div class="col-6 text-center">
  <h2><%= gettext "Welcome to %{name}!", name: "BookReads!" %></h2>
    <img src="<%= static_path(@conn, "/images/meet-book.png")%>">
</div>
<div class="col-6 text-center">
    <p class="lead">New here? Create a free account!</p>
    <%= link "Sign up", to: user_path(@conn, :new), class: "btn btn-primary btn-sm" %>&nbsp; 
    <%= link "Login" , to: user_path(@conn, :create), class: "btn btn-primary btn-sm" %>
  </div>
</div>
<hr>
<br><br>
<div class="row marketing">
  <div class="col-lg-6">
    <h4><%= link "Articles", to: article_path(@conn, :index)%></h4>
    <ul>
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides Publication</a>
      </li>
      <li>
        <a href="https://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Weblog</h4>
    <ul>
      <li>
        <a href="http://groups.google.com/group/phoenix-talk">Mailing list</a>
      </li>
      <li>
        <a href="http://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">@elixirphoenix</a>
      </li>
    </ul>
  </div>
</div>
</div>